import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { event } from 'nextjs-google-analytics'

export default function Home() {
  const onSubmit = () => {
    event('submit_form', {
      category: 'Contact',
      label: 'message',
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <button onClick={onSubmit}>Submit</button>
      </main>
    </div>
  )
}
